INSERT INTO [ROLE] (NAME, TRANS_NAME)
VALUES ('ADMIN', N'Адмін'),
       ('ENGINEER', N'Інженер'),
       ('CUSTOMER', N'Реєстратор'),
       ('ANALYST', N'Аналітик');
GO

INSERT INTO [USER] (LOGIN, EMAIL, PASSWORD, ROLE_ID)
SELECT 'admin', 'admin@admin', 'XCYOqAfSabfqEmxwkUo7Kg==:M+pelHn/19ZV3W/2sLQxNg==', ROLE.ID
FROM ROLE
WHERE NAME = 'ADMIN';
GO

INSERT INTO [STATE] (NAME, TRANS_NAME, IS_FIXED)
VALUES ('NEW', N'Нова', 1),
       ('EXECUTING', N'Виконується', 1),
       ('DONE', N'Завершена', 1),
	   ('REJECTED', N'Відхилена', 1);
GO

INSERT INTO [ACTION_TYPE] (NAME, IS_FIXED)
VALUES (N'До виконання', 1),
       (N'Завершити', 1),
       (N'Відхилити', 1);
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'NEW' AND TO_STATE.NAME = 'EXECUTING' AND ACTION_TYPE.NAME = N'До виконання';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'EXECUTING' AND TO_STATE.NAME = 'DONE' AND ACTION_TYPE.NAME = N'Завершити';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'NEW' AND TO_STATE.NAME = 'REJECTED' AND ACTION_TYPE.NAME = N'Відхилити';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'EXECUTING' AND TO_STATE.NAME = 'REJECTED' AND ACTION_TYPE.NAME = N'Відхилити';
GO

INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'Кузов');
INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'Шасі');
INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'ЕЛО');
GO

INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Зовнішнє облицювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Скління', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Внутрішнє облицювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Сидіння', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Підлога', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Поручні', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Дзеркала', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Дверні системи', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Трап', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система кондиціювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система опалення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система інформаційна', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система відеоспостереження', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вузол зчленування', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Візок привідний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Візок непривідний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Двигун дизельний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'АКПП', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Карданна передача', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вісь передня', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вісь ведуча', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Тягове обладнання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Пантограф', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Зовнішнє освітлення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Внутрішнє освітлення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Органи керування', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'АКБ', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
GO

INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Зовнішнє облицювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Зовнішнє облицювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Скління', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Скління';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Внутрішнє облицювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Внутрішнє облицювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Сидіння', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Сидіння';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Підлога', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Підлога';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Поручні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Поручні';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Дзеркала', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Дзеркала';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Дверні системи', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Дверні системи';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Трап', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Трап';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система кондиціювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система кондиціювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система опалення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система опалення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система інформаційна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система інформаційна';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система відеоспостереження', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система відеоспостереження';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вузол зчленування', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вузол зчленування';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Двигун тяговий', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Редуктор', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Муфти з’єднувальні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма дискові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма рейкові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь портальна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Елементи підвіски', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система охолодження двигунів', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система подачі піску', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система мащення реборд', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма дискові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма рейкові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь портальна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Елементи підвіски', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Муфти з’єднувальні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система живлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система мащення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система охолодження', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система нейтралізації викидів', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'АКПП', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'АКПП';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Карданна передача', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Карданна передача';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь передня', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вісь передня';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь ведуча', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вісь ведуча';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Тягове обладнання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Тягове обладнання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Пантограф', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Пантограф';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Зовнішнє освітлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Зовнішнє освітлення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Внутрішнє освітлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Внутрішнє освітлення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Органи керування', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Органи керування';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'АКБ', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'АКБ';
GO