INSERT INTO [ROLE] (NAME, TRANS_NAME)
VALUES ('ADMIN', N'Адмін'),
       ('ENGINEER', N'Інженер'),
       ('REGISTER', N'Реєстратор'),
       ('ANALYST', N'Аналітик');
GO

INSERT INTO [USER] (LOGIN, EMAIL, PASSWORD, ROLE_ID)
SELECT 'admin', 'admin@admin', 'XCYOqAfSabfqEmxwkUo7Kg==:M+pelHn/19ZV3W/2sLQxNg==', ROLE.ID
FROM ROLE
WHERE NAME = 'ADMIN';
GO

INSERT INTO [STATE] (NAME, TRANS_NAME, IS_FIXED)
VALUES ('NEW', N'Нова', 1),
       ('EXECUTING', N'Виконується', 1),
       ('DONE', N'Завершена', 1),
	   ('REJECTED', N'Відхилена', 1);
GO

INSERT INTO [ACTION_TYPE] (NAME, IS_FIXED)
VALUES (N'До виконання', 1),
       (N'Завершити', 1),
       (N'Відхилити', 1);
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'NEW' AND TO_STATE.NAME = 'EXECUTING' AND ACTION_TYPE.NAME = N'До виконання';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'EXECUTING' AND TO_STATE.NAME = 'DONE' AND ACTION_TYPE.NAME = N'Завершити';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'NEW' AND TO_STATE.NAME = 'REJECTED' AND ACTION_TYPE.NAME = N'Відхилити';
GO

INSERT INTO [TRANSITION] (FROM_STATE_ID, TO_STATE_ID, ACTION_TYPE_ID, IS_FIXED)
SELECT FROM_STATE.ID, TO_STATE.ID, ACTION_TYPE.ID, 1
FROM [STATE] AS FROM_STATE, [STATE] AS TO_STATE, [ACTION_TYPE]
WHERE FROM_STATE.NAME = 'EXECUTING' AND TO_STATE.NAME = 'REJECTED' AND ACTION_TYPE.NAME = N'Відхилити';
GO

INSERT INTO [COUNTRY] (NAME)
VALUES
    (N'Україна'),
    (N'Білорусь'),
    (N'Польща'),
    (N'Туреччина'),
    (N'Німеччина'),
    (N'Чехія'),
    (N'Росія'),
    (N'Латвія'),
    (N'Молдова'),
    (N'Фінляндія'),
    (N'Гонконг'),
    (N'Іспанія'),
    (N'Італія');
GO

INSERT INTO [CURRENCY] (SHORT_NAME, FULL_NAME)
VALUES
    (N'UAH', N'Гривня'),
    (N'USD', N'Долар'),
    (N'EUR', N'Євро'),
    (N'RUB', N'Рубль');
GO

INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Файн-Ел', N'ТОВ "Файн-Ел"', COUNTRY.ID, CURRENCY.ID, N'33233272' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СЕЙФ ГЛАСС', N'ТОВ "СЕЙФ ГЛАСС ФАКТОРІ"', COUNTRY.ID, CURRENCY.ID, N'39214213' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'AГАТ', N'ОАО "Агат - электромеханический завод"', COUNTRY.ID, CURRENCY.ID, N'н-166' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Білорусь' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Клінгспор', N'ТОВ "КЛІНГСПОР"', COUNTRY.ID, CURRENCY.ID, N'35749131' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Зовнішня реклама', N'ПП "Галицький Квалітет"', COUNTRY.ID, CURRENCY.ID, N'34509875' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВАРТЕХ', N'ТОВ "Авартех Україна"', COUNTRY.ID, CURRENCY.ID, N'40483430' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Спецсил', N'ТОВ "СПЕЦСИЛ"', COUNTRY.ID, CURRENCY.ID, N'38882880' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЕБМ-ПАПСТ', N'ТОВ "ЕБМ-ПАПСТ Україна"', COUNTRY.ID, CURRENCY.ID, N'32373159' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Укрстальпром компанія', N'ТОВ "Українська сталепромислова компанія"', COUNTRY.ID, CURRENCY.ID, N'40154619' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Полімер-Електрон', N'ДП "Завод "Полімер-Електрон"', COUNTRY.ID, CURRENCY.ID, N'23974489' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АЛЬЦЕСТ', N'Львівська філія АТ "АЛЬЦЕСТ"', COUNTRY.ID, CURRENCY.ID, N'38010565' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автономера', N'ПП "Автономера"', COUNTRY.ID, CURRENCY.ID, N'38452980' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'DEMONT', N'DEMONT Derkowski i Spolka Sp.J.', COUNTRY.ID, CURRENCY.ID, N'н-0156' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'HEMA EXIM', N'HEMA EXIM Тicaret Anonim Sirketi', COUNTRY.ID, CURRENCY.ID, N'н-155' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Туреччина' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Трайс', N'ТОВ "ТРАЙС"', COUNTRY.ID, CURRENCY.ID, N'37733364' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Металпро', N'ТОВ "Металпро"', COUNTRY.ID, CURRENCY.ID, N'41711341' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Гефелє Україна', N'ТОВ "ГЕФЕЛЄ Україна"', COUNTRY.ID, CURRENCY.ID, N'36190394' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Все для меблів', N'ТОВ "ВСЕ ДЛЯ МЕБЛІВ"', COUNTRY.ID, CURRENCY.ID, N'33396088' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ФАСТ ГРУП', N'ТОВ "ФАСТ ГРУП КОМПАНІ"', COUNTRY.ID, CURRENCY.ID, N'19319201' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АНВОЛ ЛТД', N'ТОВ ФІРМА «АНВОЛ ЛТД»', COUNTRY.ID, CURRENCY.ID, N'21484628' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Альфа-Центр', N'ТОВ «Альфа-Центр»', COUNTRY.ID, CURRENCY.ID, N'31665692' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПААЗ', N'ПАТ "Полтавський автоагрегатний завод"', COUNTRY.ID, CURRENCY.ID, N'00232124' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВЕЛВАНА', N'ТОВ "Українсько-чеське підприємство "Велвана"', COUNTRY.ID, CURRENCY.ID, N'23731918' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЕМКА', N'ТОВ "ЕМКА Україна"', COUNTRY.ID, CURRENCY.ID, N'40784103' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ФОП Булаткіна', N'ФОП Булаткіна Інна Іванівна', COUNTRY.ID, CURRENCY.ID, N'2451613527' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПРОЛІС', N'ТОВ "ПРОЛІС"', COUNTRY.ID, CURRENCY.ID, N'31888446' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Колосочок', N'ТОВ "Колосочок"', COUNTRY.ID, CURRENCY.ID, N'40105294' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СІМАТ', N'Приватне підприємство "Сімат"', COUNTRY.ID, CURRENCY.ID, N'35444426' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РІО ДОКА', N'ТОВ "РІО ДОКА"', COUNTRY.ID, CURRENCY.ID, N'38142274' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВМ Україна', N'ТОВ "ВМ Україна"', COUNTRY.ID, CURRENCY.ID, N'38855464' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Кузня Рішень', N'ТОВ "Кузня Рішень"', COUNTRY.ID, CURRENCY.ID, N'38392596' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АТОМТЕХНОЛОГІЇ', N'ТОВ "АТОМТЕХНОЛОГІЇ"', COUNTRY.ID, CURRENCY.ID, N'37806166' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Телеком-Пневматик', N'ДП "Телеком-Пневматик"', COUNTRY.ID, CURRENCY.ID, N'25591738' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'VEM', N'VEM', COUNTRY.ID, CURRENCY.ID, N'н-135' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Bonatrans', N'GNN Bonatrans', COUNTRY.ID, CURRENCY.ID, N'н-134' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Чехія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Будграніт', N'ТОВ "БУДГРАНІТ"', COUNTRY.ID, CURRENCY.ID, N'41152779' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Алькорд', N'ТОВ "АЛЬКОРД"', COUNTRY.ID, CURRENCY.ID, N'33054372' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Гураль', N'ФОП Гураль Іван Григорович', COUNTRY.ID, CURRENCY.ID, N'2093903953' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ДіВіЕс', N'ТОВ "Ді.Ві.Ес."', COUNTRY.ID, CURRENCY.ID, N'34260197' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Імпорт Консалтинг', N'ТОВ «ІМПОРТ КОНСАЛТИНГ УКРАЇНА»', COUNTRY.ID, CURRENCY.ID, N'40351894' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТУРБОГАЗ', N'ПАТ "Ужгородський турбогаз"', COUNTRY.ID, CURRENCY.ID, N'00153608' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Фіттекс', N'ТОВ "Фіттекс"', COUNTRY.ID, CURRENCY.ID, N'35252810' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Мегаболт', N'ФОП Чмихало Михайло Анатолійович', COUNTRY.ID, CURRENCY.ID, N'2819204015' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автокомпонент', N'ТОВ "АВТОКОМПОНЕНТ', COUNTRY.ID, CURRENCY.ID, N'37793690' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Востокенергомонтаж', N'компанія "Востокенергомонтаж"', COUNTRY.ID, CURRENCY.ID, N'38933458' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Олійник', N'ФОП Олійник Наталія Миколаївна', COUNTRY.ID, CURRENCY.ID, N'2407214962' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Санпаріс', N'ТОВ "Санпаріс"', COUNTRY.ID, CURRENCY.ID, N'38161559' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АМАРІ Україна', N'ТОВ "АМАРІ УКРАЇНА"', COUNTRY.ID, CURRENCY.ID, N'35138752' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'dubleks', N'Dubleks otocam sannakliyat ins.orman', COUNTRY.ID, CURRENCY.ID, N'н-0120' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Туреччина' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Вогнеборець', N'Приватне МП "Вогнеборець"', COUNTRY.ID, CURRENCY.ID, N'13807879' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Кекіс В.М.', N'ФОП Кекіс В.М.', COUNTRY.ID, CURRENCY.ID, N'3081710190' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Укратосвітло', N'ТОВ "Укравтосвітло"', COUNTRY.ID, CURRENCY.ID, N'36305686' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТД "Електрон"', N'ТОВ "ТД "Електрон"', COUNTRY.ID, CURRENCY.ID, N'40743608' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'HENSCHEL', N'HENSCHEL Antriebstechnik GmbH', COUNTRY.ID, CURRENCY.ID, N'н-115' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'NORIS', N'NORIS Automation GmbH', COUNTRY.ID, CURRENCY.ID, N'н-114' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Lenord', N'Lenord, Bauer & Co. GmbH', COUNTRY.ID, CURRENCY.ID, N'н-113' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'GEREP', N'GEREP Maschinenbau GmbH', COUNTRY.ID, CURRENCY.ID, N'н-112' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Промінструмент', N'ТОВ "ВІР-ПРОМІНСТРУМЕНТ"', COUNTRY.ID, CURRENCY.ID, N'39906315' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сувенір ВТС', N'ТОВ "ВТС СУВЕНІР"', COUNTRY.ID, CURRENCY.ID, N'34577285' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Хімпромгурт', N'ТОВ "Хімпромгурт"', COUNTRY.ID, CURRENCY.ID, N'30477609' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Швид.пром.допом.', N'ПП "Швидка Промислова Допомога"', COUNTRY.ID, CURRENCY.ID, N'37123491' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КАРАВЕЛА ГРУП', N'ТОВ "КАРАВЕЛА ГРУП"', COUNTRY.ID, CURRENCY.ID, N'40158393' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПУЛЬСАР', N'ТОВ-компанія «Пульсар і Ко»', COUNTRY.ID, CURRENCY.ID, N'30712238' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СВІДІС', N'ТОВ "СВІДІС Україна"', COUNTRY.ID, CURRENCY.ID, N'40370524' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Рембуд-лайн', N'ТОВ "Рембуд-лайн"', COUNTRY.ID, CURRENCY.ID, N'40232073' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Яскорська', N'ФОП Яскорська', COUNTRY.ID, CURRENCY.ID, N'2769907664' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЄВРАЗТРЕЙД', N'ТОВ "Євразтрейд"', COUNTRY.ID, CURRENCY.ID, N'39534261' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інпром', N'ТОВ "МК Інпром"', COUNTRY.ID, CURRENCY.ID, N'39524101' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інтербуд', N'ТОВ "Ітербуд-Вест"', COUNTRY.ID, CURRENCY.ID, N'34418987' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Подарєва Н.М.', N'СПД Подарєва Наталія Михайлівна (Модус)', COUNTRY.ID, CURRENCY.ID, N'1707301524' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КОПКО', N'ФОП Копко А.В.', COUNTRY.ID, CURRENCY.ID, N'31009167' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЛОГІСТИК', N'ТОВ "Ауріс ЛОГІСТИК"', COUNTRY.ID, CURRENCY.ID, N'39430244' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Фурнітура', N'ТК Фурнітура', COUNTRY.ID, CURRENCY.ID, N'30606259' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Склоресурс', N'ТОВ "Склоресурс"', COUNTRY.ID, CURRENCY.ID, N'34629505' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автоцентр ЕРА', N'ПП Автоцентр "ЕРА"', COUNTRY.ID, CURRENCY.ID, N'33665762' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Браш', N'Товариство з обмеженою відповідальністю "Браш"', COUNTRY.ID, CURRENCY.ID, N'33914746' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Господар', N'ПП "МОН АВІ"', COUNTRY.ID, CURRENCY.ID, N'37560352' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Чернихівський', N'ФОП Чернихівський Михайло Іванович', COUNTRY.ID, CURRENCY.ID, N'3025805877' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Поиск', N'ПП "НВФ "Поиск"', COUNTRY.ID, CURRENCY.ID, N'23496040' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ХІМІМПЕКС', N'СУЛП "Хімімпекс"', COUNTRY.ID, CURRENCY.ID, N'14345702' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РЕГІОН-04', N'ПП "Регіон-04"', COUNTRY.ID, CURRENCY.ID, N'32759862' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КОМТЕК', N'ТОВ "Комтек-Сервіс"', COUNTRY.ID, CURRENCY.ID, N'37065063' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Данило', N'ТОВ "Рубікон-Інтер"', COUNTRY.ID, CURRENCY.ID, N'39179656' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'БРАЗ', N'ТОВ "Броварський Алюмінієвий Завод"', COUNTRY.ID, CURRENCY.ID, N'38108144' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ФРУНЗЕ', N'ПАТ "Завод Фрунзе"', COUNTRY.ID, CURRENCY.ID, N'00236010' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВЕР ТЕХ', N'ТОВ "Авер-ТЕХ"', COUNTRY.ID, CURRENCY.ID, N'21665318' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ІСХОНІЯ', N'ПП "Ісхонія"', COUNTRY.ID, CURRENCY.ID, N'32800378' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'УКРІНТЕГРО 2006', N'ТОВ "УКРІНТЕГРО 2006"', COUNTRY.ID, CURRENCY.ID, N'34185686' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Мікроприлад', N'ТОВ "Мікроприлад"', COUNTRY.ID, CURRENCY.ID, N'23728738' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КПП ЦЕНТР', N'ТОВ "КПП ЦЕНТР" Strans', COUNTRY.ID, CURRENCY.ID, N'38169102' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Хімрезерв', N'ТОВ "Хімрезерв-Львів"', COUNTRY.ID, CURRENCY.ID, N'34029478' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інтер-Запчастина', N'ТОВ "Інтер-Запчастина"', COUNTRY.ID, CURRENCY.ID, N'400054444' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РІФ-03', N'ТОВ "РІФ-03"', COUNTRY.ID, CURRENCY.ID, N'32463294' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТАЛЯ', N'МПП "Таля"', COUNTRY.ID, CURRENCY.ID, N'20540365' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПРОМФАКТОР', N'ТОВ "Промфактор"', COUNTRY.ID, CURRENCY.ID, N'25019584' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'САВА', N'ТОВ "Сава"', COUNTRY.ID, CURRENCY.ID, N'32099297' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'УГМК', N'ПАТ "Українська гірничо-металургійна компанія"', COUNTRY.ID, CURRENCY.ID, N'35725791' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЄВРОПРОЕКТ-ЗАХІД', N'ТОВ "Європроект-Захід"', COUNTRY.ID, CURRENCY.ID, N'34559187' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Єременко', N'ФОП Єременко Д.В.', COUNTRY.ID, CURRENCY.ID, N'3006409933' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВІРТУОЗ', N'ТОВ Виробнича фірма "Віртуоз і КО"', COUNTRY.ID, CURRENCY.ID, N'40199230' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АГЕНА ЮА', N'ТОВ "Агена ЮА"', COUNTRY.ID, CURRENCY.ID, N'39246067' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АЛЬФА ЛЛС', N'ТОВ "Альфа ЛЛС"', COUNTRY.ID, CURRENCY.ID, N'38104066' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЗОЛОТИЙ ВІК', N'ТОВ "Золотий вік"', COUNTRY.ID, CURRENCY.ID, N'20840104' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Нова мережа', N'ПП Нова мережа', COUNTRY.ID, CURRENCY.ID, N'34857976' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Чернівецький хімзавод', N'ТДВ "Чернівецький хімзавод"', COUNTRY.ID, CURRENCY.ID, N'00204665' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Харелектротранс', N'ТОВ "ХАРЕЛЕКТРОТРАНС"', COUNTRY.ID, CURRENCY.ID, N'22652358' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Марікуца', N'ФОП Марікуца Ю.А.', COUNTRY.ID, CURRENCY.ID, N'254040832' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АТОМ', N'МПП "АТОМ"', COUNTRY.ID, CURRENCY.ID, N'13807715' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ДЕСТА', N'ПП ДЕСТА', COUNTRY.ID, CURRENCY.ID, N'21099089' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КОНТАКТ', N'КОПП "КОНТАКТ" УТОГ', COUNTRY.ID, CURRENCY.ID, N'03972620' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електрон-Т', N'ТОВ НВП «Електрон-Т»', COUNTRY.ID, CURRENCY.ID, N'00244676' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КОМП’ЮТЕРІНФО', N'ПП "Комп’ютерінфо та сучасні технології"', COUNTRY.ID, CURRENCY.ID, N'32484356' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ШААЗ', N'АО "Шадринский автоагрегатный завод"', COUNTRY.ID, CURRENCY.ID, N'н-0450' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РІСТ', N'ТОВ НВП "РІСТ"', COUNTRY.ID, CURRENCY.ID, N'25221038' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВЕЕМ-Металавтопром', N'ТОВ "Компанія ВЕЕМ-Металавтопром"', COUNTRY.ID, CURRENCY.ID, N'30994335' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Графік Стар', N'ТОВ "Графік Стар"', COUNTRY.ID, CURRENCY.ID, N'37655978' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Гідравлік мастер', N'ТОВ "Гідравлік мастер", офіційний дистрибютор Henkel', COUNTRY.ID, CURRENCY.ID, N'37316467' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Тавор', N'ТОВ "ТАВОР"', COUNTRY.ID, CURRENCY.ID, N'30613470' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сталь Холдинг', N'ТОВ "Сталь Холдинг"', COUNTRY.ID, CURRENCY.ID, N'39993345' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Тедекс Мастила Україна', N'ПП "Тедекс Мастила Україна"', COUNTRY.ID, CURRENCY.ID, N'34943074' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Жираф', N'ТОВ "ТМ "Жираф"', COUNTRY.ID, CURRENCY.ID, N'38397971' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Врублевський А.В', N'ПП Врублевський А.В', COUNTRY.ID, CURRENCY.ID, N'1778314911' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Альянс Холдінг', N'ТОВ "Альянс Холдінг"', COUNTRY.ID, CURRENCY.ID, N'34430873' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Eкран', N'ОАО "Экран"', COUNTRY.ID, CURRENCY.ID, N'37502' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Білорусь' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ДВЗ', N'ООО "Димитровградский вентильный завод"', COUNTRY.ID, CURRENCY.ID, N'00705' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Врублевська Г.М.', N'ПП Врублевська Г. М.', COUNTRY.ID, CURRENCY.ID, N'1762304084' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ZF LEMFÖRDER', N'ZF LEMFÖRDER', COUNTRY.ID, CURRENCY.ID, N'04918' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'VEGAAUTO', N'Інтернет магазин "VEGAAUTO"', COUNTRY.ID, CURRENCY.ID, N'н-0405' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВЕКТОР-ВС', N'ТОВ "ТВК ВЕКТОР-ВС"', COUNTRY.ID, CURRENCY.ID, N'37625571' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Knorr-Bremse', N'Knorr-Bremse Fekrendszerek Kft.', COUNTRY.ID, CURRENCY.ID, N'н-0403' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Dinex', N'Dinex Latvia pardosana', COUNTRY.ID, CURRENCY.ID, N'04812' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Латвія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СТОМІЛЬ САНОК', N'ТОВ "СТОМІЛЬ САНОК УКРАЇНА"', COUNTRY.ID, CURRENCY.ID, N'35953560' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Cummins', N'Cummins Ltd Sp. z o.o.', COUNTRY.ID, CURRENCY.ID, N'04810' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'BSPL', N'BSPL', COUNTRY.ID, CURRENCY.ID, N'04809' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'BOSCH', N'Robert Bosch Automotive Steering Gmbh', COUNTRY.ID, CURRENCY.ID, N'04917' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Ковальський Ю.М.', N'ФОП Ковальський Ю. М.', COUNTRY.ID, CURRENCY.ID, N'3235909275' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Цефей сервіс', N'ТОВ "ЦЕФЕЙ СЕРВІС"', COUNTRY.ID, CURRENCY.ID, N'39434296' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Фанери та плити', N'ПрАТ "Фанери та плити"', COUNTRY.ID, CURRENCY.ID, N'00274690' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'УПП УТОС', N'Білоцерківське УПП УТОС', COUNTRY.ID, CURRENCY.ID, N'9107' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Тростинський І.І.', N'ФОП Тростинський І. І.', COUNTRY.ID, CURRENCY.ID, N'1807014514' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Ніка Ейр', N'ТОВ "Ніка Ейр"', COUNTRY.ID, CURRENCY.ID, N'39600370' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Метал Холдінг', N'ТОВ «Метал Холдінг Львів»', COUNTRY.ID, CURRENCY.ID, N'33286209' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Колорспіріт', N'ТОВ "Колорспіріт"', COUNTRY.ID, CURRENCY.ID, N'38799447' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Шевчук І.М.', N'СПД ФО Шевчук І. М', COUNTRY.ID, CURRENCY.ID, N'2055504012' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КБП Україна', N'ТОВ «Завод КБП Україна»', COUNTRY.ID, CURRENCY.ID, N'39176676' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електронмаш', N'Завод "ЕЛЕКТРОНМАШ"-ДП ПАТ "КОНЦЕРН ЕЛЕКТРОН"', COUNTRY.ID, CURRENCY.ID, N'38172658' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Еберспехер', N'ТОВ "Еберспехер Україна"', COUNTRY.ID, CURRENCY.ID, N'33740205' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автомоторс', N'ДП "Автомоторс"', COUNTRY.ID, CURRENCY.ID, N'31828113' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КрКЗ', N'ПАТ "Кременчуцький колісний завод"', COUNTRY.ID, CURRENCY.ID, N'00231610' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Астра-Бразерс', N'ТОВ "Астра-Бразерс"', COUNTRY.ID, CURRENCY.ID, N'32081316' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Каравелла', N'ТОВ Компанія "Каравелла"', COUNTRY.ID, CURRENCY.ID, N'36670052' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Промлітсплав', N'ТОВ "Промлітсплав"', COUNTRY.ID, CURRENCY.ID, N'39381653' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КЕРХЕР', N'ТОВ "КЕРХЕР"', COUNTRY.ID, CURRENCY.ID, N'34003237' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Технооптторг-трейд', N'ТОВ "Технооптторг-трейд"', COUNTRY.ID, CURRENCY.ID, N'31497076' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Хаммер', N'ТОВ «Хаммер»', COUNTRY.ID, CURRENCY.ID, N'н-0377' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Юнона', N'ТОВ "Юнона"', COUNTRY.ID, CURRENCY.ID, N'20841865' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЭТОН', N'УП "ЭТОН-ЭЛТРАНС"', COUNTRY.ID, CURRENCY.ID, N'37501' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Білорусь' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Электромаш', N'ООО "ТД Электромаш"', COUNTRY.ID, CURRENCY.ID, N'00704' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЧПЗ', N'ПАТ "Черкаський приладобудівний завод"', COUNTRY.ID, CURRENCY.ID, N'н-0370' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Цірцея', N'ПП "Цірцея"', COUNTRY.ID, CURRENCY.ID, N'23270280' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Грушецький О.Р.', N'ФОП Грушецький Олег Романович', COUNTRY.ID, CURRENCY.ID, N'2870404052' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Батршин О.З.', N'ФОП Батршин Олексій Закірович', COUNTRY.ID, CURRENCY.ID, N'н-0367' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Фенiкс Контакт', N'ТОВ "Фенiкс Контакт"', COUNTRY.ID, CURRENCY.ID, N'33497772' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'УТОС', N'Черкаське "УВП "УТОС"', COUNTRY.ID, CURRENCY.ID, N'03967955' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТУБЕС Інт.', N'ТОВ "ТУБЕС Інтернешнл ТОВ"', COUNTRY.ID, CURRENCY.ID, N'33562712' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Ексім-авто', N'ПП "Ексім-авто"', COUNTRY.ID, CURRENCY.ID, N'31729677' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТОВ "Авто-Ком-Деталь"', N'ТОВ "Авто-Ком-Деталь"', COUNTRY.ID, CURRENCY.ID, N'38998049' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Технос', N'ООО "Технос"', COUNTRY.ID, CURRENCY.ID, N'00703' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТДК', N'ТОВ "ТД "Троси дистанційного керування"', COUNTRY.ID, CURRENCY.ID, N'31003530' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТД Папір', N'ТОВ Торговий дім "Папір"', COUNTRY.ID, CURRENCY.ID, N'31064499' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТД "ДС"', N'ТОВ "Торгівельний дім "ДС"', COUNTRY.ID, CURRENCY.ID, N'н-0358' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СТІЛХАРТ', N'ТОВ "Стілхарт"', COUNTRY.ID, CURRENCY.ID, N'39307737' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Стандартавто', N'ПП "Стандартавто"', COUNTRY.ID, CURRENCY.ID, N'38325603' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Стальоптторг', N'ТОВ "Стальоптторг"', COUNTRY.ID, CURRENCY.ID, N'38375937' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СПК-Україна', N'ТОВ "Сталепромислова компанія-Україна"', COUNTRY.ID, CURRENCY.ID, N'39113574' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Миколишин В.М.', N'СПД-ФО Миколишин В. М.', COUNTRY.ID, CURRENCY.ID, N'2455102112' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Союз-Торг', N'ТОВ "САНПАРІС"', COUNTRY.ID, CURRENCY.ID, N'38161559' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Славія', N'ПП "Славія"', COUNTRY.ID, CURRENCY.ID, N'21325462' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СКІФ-КОНТРОЛ', N'ТОВ "СКІФ-КОНТРОЛ"', COUNTRY.ID, CURRENCY.ID, N'19254269' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Скайф груп', N'ТОВ "Скайф груп"', COUNTRY.ID, CURRENCY.ID, N'39115110' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сервісцентр НПК', N'ТОВ "Сервісний центр "НПК"', COUNTRY.ID, CURRENCY.ID, N'33462312' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сервіспостач', N'ПП "Сервіс-Постач"', COUNTRY.ID, CURRENCY.ID, N'35854397' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СенКо', N'ТОВ "ФОНТЕК-С"', COUNTRY.ID, CURRENCY.ID, N'36051531' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СДС', N'ТОВ "Системи дистрибуції та сервісу"', COUNTRY.ID, CURRENCY.ID, N'33880229' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'САДА', N'ПАТ Акумуляторний завод "САДА"', COUNTRY.ID, CURRENCY.ID, N'24962494' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Росукрелпром', N'ТОВ "Росукрелпром"', COUNTRY.ID, CURRENCY.ID, N'37201972' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Ресурс-Метал', N'ТОВ "Ресурс-Метал"', COUNTRY.ID, CURRENCY.ID, N'38833498' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Радій', N'ПАТ "НВП "Радій"', COUNTRY.ID, CURRENCY.ID, N'14312430' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПЭМЗ', N'ПЭМЗ', COUNTRY.ID, CURRENCY.ID, N'00702' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Простір-Груп', N'ТОВ "Простір-Груп"', COUNTRY.ID, CURRENCY.ID, N'37045106' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Промтрансенерго', N'ТОВ НВП "Промтрансенерго"', COUNTRY.ID, CURRENCY.ID, N'21100912' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Промелектробуд', N'ТОВ "Промелектробуд"', COUNTRY.ID, CURRENCY.ID, N'38923167' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПП Чепіль', N'ПП Чепіль', COUNTRY.ID, CURRENCY.ID, N'н-0331' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Постачгарант', N'ТОВ "Постачгарант"', COUNTRY.ID, CURRENCY.ID, N'39217874' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Полімерконтейнер', N'ТОВ "Харківський завод "Полімерконтейнер"', COUNTRY.ID, CURRENCY.ID, N'н-0325' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ПОЛІЕСТЕР', N'ТОВ "УМС ПОЛІЕСТЕР"', COUNTRY.ID, CURRENCY.ID, N'35980924' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Пліт', N'ВКФ "Пліт"', COUNTRY.ID, CURRENCY.ID, N'22339868' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Пластикс Україна', N'ТОВ "Пластікс Україна"', COUNTRY.ID, CURRENCY.ID, N'24587464' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Оріон', N'ТОВ "ТДК Оріон"', COUNTRY.ID, CURRENCY.ID, N'38526239' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Орієнтир', N'СКЦ «Орієнтир»', COUNTRY.ID, CURRENCY.ID, N'22333765' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ОксигенЗахід', N'ПП "ОксигенЗахід"', COUNTRY.ID, CURRENCY.ID, N'36873888' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Одескабель', N'ТОРГОВИЙ ДІМ ОДЕСЬКОГО КАБЕЛЬНОГО ЗАВОДУ "ОДЕСКАБЕЛЬ"', COUNTRY.ID, CURRENCY.ID, N'30332681' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ОДЕК Україна', N'ТОВ "ОДЕК Україна"', COUNTRY.ID, CURRENCY.ID, N'25322516' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Нормета', N'ТОВ "Нормета"', COUNTRY.ID, CURRENCY.ID, N'31851683' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'НІКТАДІНА-95', N'ТОВ НВП "НІКТАДІНА-95"', COUNTRY.ID, CURRENCY.ID, N'23935325' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'МОСОО', N'ПП "МОСОО"', COUNTRY.ID, CURRENCY.ID, N'20218221' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'МОДУС', N'ТОВ "ТД "МОДУС"', COUNTRY.ID, CURRENCY.ID, N'39364638' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Мета-Импекс', N'ТОВ "Мета-Импекс"', COUNTRY.ID, CURRENCY.ID, N'32564368' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Мезон-електрокабель', N'ДП "Мезон-електрокабель"', COUNTRY.ID, CURRENCY.ID, N'30583368' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Марка', N'ТОВ "ПП Марка"', COUNTRY.ID, CURRENCY.ID, N'40945483' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'МАККОМ', N'ТОВ "МАККОМ"', COUNTRY.ID, CURRENCY.ID, N'31362979' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Магна-Трейд', N'ПП "Магна-Трейд", дистрибютор Henkel, Loctite', COUNTRY.ID, CURRENCY.ID, N'36767680' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Львівсинтез', N'ПП "Львівсинтез"', COUNTRY.ID, CURRENCY.ID, N'19169204' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Львівпідшипник', N'ТОВ "Львівпідшипник"', COUNTRY.ID, CURRENCY.ID, N'20787025' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Львівкольормет-2', N'ТОВ "Львівкольормет-2"', COUNTRY.ID, CURRENCY.ID, N'37205411' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЛТАВА', N'ПАТ "Завод "ЛТАВА"', COUNTRY.ID, CURRENCY.ID, N'14308479' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЛМВ-33', N'ТОВ "Сімбад"', COUNTRY.ID, CURRENCY.ID, N'34839119' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЛИТПРОМ', N'ТОВ "ВКП "ЛІТПРОМ"', COUNTRY.ID, CURRENCY.ID, N'36986430' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЛАПП', N'ТОВ "ЛАПП Україна"', COUNTRY.ID, CURRENCY.ID, N'32310523' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Ланквітцер', N'ДП "Ланквітцер-Україна', COUNTRY.ID, CURRENCY.ID, N'31290674' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КЭАЗ', N'Компанія "КЕАЗ ГРУП"', COUNTRY.ID, CURRENCY.ID, N'23072410' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Кредув', N'ТОВ "ПКВП Крєдув"', COUNTRY.ID, CURRENCY.ID, N'36828341' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КРАЗ', N'ПАТ "АВТОКРАЗ"', COUNTRY.ID, CURRENCY.ID, N'05808735' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КПЕМЗ', N'ТОВ "Кам’янець-Подільський електромеханічний завод"', COUNTRY.ID, CURRENCY.ID, N'00213807' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Консалтинг Мегабуд', N'ТОВ "Консалтинг Мегабуд"', COUNTRY.ID, CURRENCY.ID, N'37831600' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Солісіт', N'ТОВ "Компанія "Солісіт"', COUNTRY.ID, CURRENCY.ID, N'34185691' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КоДІС', N'ТОВ "НТП "КоДІС"', COUNTRY.ID, CURRENCY.ID, N'32769155' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Кершер Плюс', N'ТОВ "Кершер Плюс"', COUNTRY.ID, CURRENCY.ID, N'31514845' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'КЕАЗ ГРУП', N'ТОВ "КЕАЗ ГРУП"', COUNTRY.ID, CURRENCY.ID, N'23072410' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Карго Партс', N'ТОВ "КАРГО ПАРТС"', COUNTRY.ID, CURRENCY.ID, N'33398771' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інф.екс.центр', N'ТОВ "Інф.-екс.центр Радіоелектроніки"', COUNTRY.ID, CURRENCY.ID, N'34634164' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інвар', N'ТОВ "НВП "Інвар"', COUNTRY.ID, CURRENCY.ID, N'13823660' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ИРБИС-СЕРВІС', N'ТОВ "ИРБИС-СЕРВІС"', COUNTRY.ID, CURRENCY.ID, N'33289530' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЗЮВС', N'ТОВ "НТКФ "ЗЮВС', COUNTRY.ID, CURRENCY.ID, N'20825180' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Згода', N'ТОВ "ТД "Згода"', COUNTRY.ID, CURRENCY.ID, N'36648635' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Еталонтрейд', N'ТОВ "Еталонтрейд"', COUNTRY.ID, CURRENCY.ID, N'38488026' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Епіцентр К', N'ТОВ "Епіцентр К"', COUNTRY.ID, CURRENCY.ID, N'32490244' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Енергомаш', N'ТОВ "Виробничо-торгівельна компанія "Енергомаш"', COUNTRY.ID, CURRENCY.ID, N'33112952' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Елемент-Перетворювач', N'ТОВ "Елемент-Перетворювач"', COUNTRY.ID, CURRENCY.ID, N'30077685' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електропромсервіс', N'ПП «Електропромсервіс»', COUNTRY.ID, CURRENCY.ID, N'31074973' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електронпобутприлад', N'ТОВ "Завод Електронпобутприлад"', COUNTRY.ID, CURRENCY.ID, N'30650679' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ТЗ "Електрон"', N'Телевізійний завод "Електрон"-дочірнє підприємство ПАТ "Концерн-Електрон"', COUNTRY.ID, CURRENCY.ID, N'32969709' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електротяжмаш', N'ДП "Завод Електроважмаш"', COUNTRY.ID, CURRENCY.ID, N'00213121' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЕКСЕЛ', N'ПП "ЕКСЕЛ"', COUNTRY.ID, CURRENCY.ID, N'32873844' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Екосистем', N'ТОВ "Центр іноваційних технологій "Екосистем"', COUNTRY.ID, CURRENCY.ID, N'36867593' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Евдіаліт', N'ПП "ЕВДІАЛІТ"', COUNTRY.ID, CURRENCY.ID, N'38389295' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ДС-Техно', N'"ДС-Техно"', COUNTRY.ID, CURRENCY.ID, N'88601' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Донтехгума', N'Командитне товариство "Донтехгума і Компанія"', COUNTRY.ID, CURRENCY.ID, N'00152342' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Дельта-ком', N'ТОВ "Дельта-ком"', COUNTRY.ID, CURRENCY.ID, N'37035290' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ДАСк-Центр', N'ПП "ДАСк-Центр"', COUNTRY.ID, CURRENCY.ID, N'24430567' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Гранато', N'ТОВ НВФ "Гранато"', COUNTRY.ID, CURRENCY.ID, N'14305453' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Глухів Електропанель', N'ПАТ "Глухівський завод Електропанель"', COUNTRY.ID, CURRENCY.ID, N'00213764' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ГерКо', N'ТОВ "ГерКо"', COUNTRY.ID, CURRENCY.ID, N'37584368' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Галпостачсервіс', N'ПП "Галпостачсервіс"', COUNTRY.ID, CURRENCY.ID, N'22374051' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Галенерго', N'ПП "Галенерго"', COUNTRY.ID, CURRENCY.ID, N'34462266' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ГАЛАВТОМЕТ', N'ТОВ "СП ГАЛАВТОМЕТ"', COUNTRY.ID, CURRENCY.ID, N'38667366' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Вольтаж', N'ТОВ "Вольтаж"', COUNTRY.ID, CURRENCY.ID, N'36879279' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Бусол', N'ТОВ НВФ "Бусол"', COUNTRY.ID, CURRENCY.ID, N'14096564' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'БіоХімАкт', N'ВАТ "БіоХімАкт"', COUNTRY.ID, CURRENCY.ID, N'н-0251' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Бентелер', N'ТОВ "Бентелер Дістріб’юшн Україна"', COUNTRY.ID, CURRENCY.ID, N'36248391' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Бендери', N'Бендерский ЗЭА', COUNTRY.ID, CURRENCY.ID, N'н-0249' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Молдова' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Бабій Я.В.', N'ПП Бабій Ярослав Васильович', COUNTRY.ID, CURRENCY.ID, N'2137012254' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АМК ТРЕЙД', N'ТОВ "АМК ТРЕЙД"  Schlemmer', COUNTRY.ID, CURRENCY.ID, N'37797040' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АльфаТрансГруп', N'ТОВ "АльфаТрансГруп"', COUNTRY.ID, CURRENCY.ID, N'32523630' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Альтера-Львів', N'ТОВ "СВ Альтера-Львів"', COUNTRY.ID, CURRENCY.ID, N'33252232' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Альтера', N'ТОВ "Альтера Просистем"', COUNTRY.ID, CURRENCY.ID, N'38852987' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Алінокс', N'ТОВ "Алінокс Україна"', COUNTRY.ID, CURRENCY.ID, N'37800990' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АККУ-ЕНЕРГО', N'ТОВ "АККУ-ЕНЕРГО"', COUNTRY.ID, CURRENCY.ID, N'31902769' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АвтоСтандарт', N'ТОВ "Авто Стандарт Україна"', COUNTRY.ID, CURRENCY.ID, N'35775727' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВТЕЙ', N'Спеціалізований магазин автозапчастин "Автей"', COUNTRY.ID, CURRENCY.ID, N'1484904865' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автоелектроапаратура', N'ПрАТ "Автоелектроапаратура"', COUNTRY.ID, CURRENCY.ID, N'32192547' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Автоагрегат', N'ПАТ "Краснодонський завод "Автоагрегат"', COUNTRY.ID, CURRENCY.ID, N'00231290' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Авеаль', N'ТОВ "Авеаль"', COUNTRY.ID, CURRENCY.ID, N'38648500' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВАЛОН', N'ПП "АВАЛОН 2002"', COUNTRY.ID, CURRENCY.ID, N'32180068' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВ ЦЕНТР', N'ТОВ ФІРМА "АВ ЦЕНТР"', COUNTRY.ID, CURRENCY.ID, N'20028822' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АББ Лтд', N'ТОВ АББ Лтд, дилер "Нова мережа"', COUNTRY.ID, CURRENCY.ID, N'21664678' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АВ металгруп', N'ТОВ "АВ метал груп"', COUNTRY.ID, CURRENCY.ID, N'36441934' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ZF Friedrichshafen', N'ZF Friedrichshafen AG', COUNTRY.ID, CURRENCY.ID, N'н-0230' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ZF Passau', N'ZF Passau GmbH', COUNTRY.ID, CURRENCY.ID, N'04915' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'WPH', N'Wytwórnia Pomp Hydraulicznych Sp. z o.o.', COUNTRY.ID, CURRENCY.ID, N'04808' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'WIT-MOT', N'FPUH WIT-MOT Witkowski Piotr', COUNTRY.ID, CURRENCY.ID, N'04807' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'UN WHA', N'UN WHA Poland Ltd.', COUNTRY.ID, CURRENCY.ID, N'04806' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'TriboTec', N'TriboTec, spol. s r.o.', COUNTRY.ID, CURRENCY.ID, N'42002' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Чехія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Toga', N'Toga TG Sp.o.o', COUNTRY.ID, CURRENCY.ID, N'04805' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Techem', N'BP Techem S A', COUNTRY.ID, CURRENCY.ID, N'04804' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Tamware', N'Oy Tamware AB', COUNTRY.ID, CURRENCY.ID, N'35801' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Фінляндія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сіка', N'ТОВ "Сіка Україна"', COUNTRY.ID, CURRENCY.ID, N'33053410' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'REVAR', N'REVAR Otomotiv San.ve Tic. A.S.', COUNTRY.ID, CURRENCY.ID, N'09002' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Туреччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'PILOT', N'PILOT TASIT KOLTUKLARI SANAYI VE TICARET A.S.', COUNTRY.ID, CURRENCY.ID, N'09004' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Туреччина' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'PAILTON', N'PAILTON', COUNTRY.ID, CURRENCY.ID, N'04913' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'MVM', N'MVM', COUNTRY.ID, CURRENCY.ID, N'85201' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Гонконг' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'MEKRA', N'MEKRA Lang GmbH & Co. KG', COUNTRY.ID, CURRENCY.ID, N'04912' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Mawer', N'Mawer GmbH', COUNTRY.ID, CURRENCY.ID, N'04911' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Klein', N'Eugen Klein GmbH', COUNTRY.ID, CURRENCY.ID, N'04910' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'EV-Power', N'Global World Logistic Ltd.', COUNTRY.ID, CURRENCY.ID, N'42001' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Чехія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ERA Elektronik', N'EMSAT Elektronik Mallar San. Ve Tic. A.S', COUNTRY.ID, CURRENCY.ID, N'09001' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Туреччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Elephant', N'Elephant', COUNTRY.ID, CURRENCY.ID, N'04909' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'EC Engineering', N'EC Engineering', COUNTRY.ID, CURRENCY.ID, N'04803' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'DOGA', N'DOGA', COUNTRY.ID, CURRENCY.ID, N'04908' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Іспанія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СDC-Україна', N'ТОВ "CDC-Україна"', COUNTRY.ID, CURRENCY.ID, N'н-0205' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Камоцці-Львів', N'ТОВ "Камоцці"', COUNTRY.ID, CURRENCY.ID, N'14290527' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'AGB', N'AGB', COUNTRY.ID, CURRENCY.ID, N'03901' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Італія' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АD Шина', N'ТОВ "АД ШИНА"', COUNTRY.ID, CURRENCY.ID, N'35974863' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ABUS', N'ABUS', COUNTRY.ID, CURRENCY.ID, N'04907' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'BINZEL', N'ABICOR BINZEL', COUNTRY.ID, CURRENCY.ID, N'04906' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РАТУС', N'ТОВ "РАТУС"', COUNTRY.ID, CURRENCY.ID, N'34605552' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Інтеграс', N'ПП "Інтеграс"', COUNTRY.ID, CURRENCY.ID, N'35586431' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Київгума', N'ТОВ "Київгума"', COUNTRY.ID, CURRENCY.ID, N'35115248' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'HANNING & KAHL', N'HANNING & KAHL GmbH & Co. KG', COUNTRY.ID, CURRENCY.ID, N'04905' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Юстас-К', N'ПП "Юстас-К"', COUNTRY.ID, CURRENCY.ID, N'32568467' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ENIKA', N'ENIKA Sp. z o.o.', COUNTRY.ID, CURRENCY.ID, N'04802' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'El-cab', N'El-Cab Sp. z o.o.', COUNTRY.ID, CURRENCY.ID, N'04801' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ЧЕРГОС', N'ООО "ЧЕРГОС"', COUNTRY.ID, CURRENCY.ID, N'00701' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Росія' AND CURRENCY.SHORT_NAME = N'RUB';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ВІАКОМ', N'ТОВ "ВІАКОМ"', COUNTRY.ID, CURRENCY.ID, N'24937160' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ІРБІС', N'ТОВ "ТД ІРБІС"', COUNTRY.ID, CURRENCY.ID, N'31559190' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Електромайстер', N'ПП "Електромайстер"', COUNTRY.ID, CURRENCY.ID, N'33073809' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'СФЕРОС-ЕЛЕКТРОН', N'СП ТОВ "СФЕРОС-ЕЛЕКТРОН"', COUNTRY.ID, CURRENCY.ID, N'23972496' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'REMEZA', N'ЗАО "Ремеза"', COUNTRY.ID, CURRENCY.ID, N'н-0118' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Білорусь' AND CURRENCY.SHORT_NAME = N'USD';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ІнтерПЕТ', N'ТОВ "ІнтерПЕТ"', COUNTRY.ID, CURRENCY.ID, N'30492103' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'TransTec', N'TransTec Vetschau GmbH', COUNTRY.ID, CURRENCY.ID, N'04903' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'ОРІОН ГЛАСС', N'ТОВ "ОРІОН-ГЛАСС СК"', COUNTRY.ID, CURRENCY.ID, N'31476297' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сміла', N'ТОВ "СМІЛЯНСЬКИЙ ЛИВАРНИЙ ЗАВОД"', COUNTRY.ID, CURRENCY.ID, N'35505844' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'РКС Компоненти', N'ТОВ "РКС Компоненти Україна"', COUNTRY.ID, CURRENCY.ID, N'39087398' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Сімметрон', N'ТОВ "Сімметрон-Україна"', COUNTRY.ID, CURRENCY.ID, N'31089864' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'Хімтекстиль', N'ТОВ "ХІМТЕКСТИЛЬ"', COUNTRY.ID, CURRENCY.ID, N'23292264' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АСКО', N'Корпорація ACKO-УКРЕМ', COUNTRY.ID, CURRENCY.ID, N'33880124' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'SIRIT', N'SIRIT POLAND Sp. zo.o', COUNTRY.ID, CURRENCY.ID, N'н-0104' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Польща' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'WABCO', N'Wabco Austria GesmbH', COUNTRY.ID, CURRENCY.ID, N'н-0103' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Німеччина' AND CURRENCY.SHORT_NAME = N'EUR';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'МETALVIS', N'ЛФ "Солді-Львів"', COUNTRY.ID, CURRENCY.ID, N'23162981' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'НАК', N'ТОВ ТПК "НАК"', COUNTRY.ID, CURRENCY.ID, N'31073990' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
INSERT INTO [SUPPLIER] (NAME, FULL_NAME, COUNTRY, CURRENCY, EDRPOU) SELECT N'АІС АЗЧ МАРКЕT', N'ТОВ "АІС АЗЧ МАРКЕТ"', COUNTRY.ID, CURRENCY.ID, N'33100549' FROM COUNTRY, CURRENCY WHERE COUNTRY.NAME = N'Україна' AND CURRENCY.SHORT_NAME = N'UAH';
GO

INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'Кузов');
INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'Шасі');
INSERT INTO MALFUNCTION_GROUP(NAME) VALUES(N'ЕЛО');
GO

INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Зовнішнє облицювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Скління', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Внутрішнє облицювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Сидіння', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Підлога', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Поручні', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Дзеркала', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Дверні системи', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Трап', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система кондиціювання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система опалення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система інформаційна', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Система відеоспостереження', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вузол зчленування', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Кузов';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Візок привідний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Візок непривідний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Двигун дизельний', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'АКПП', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Карданна передача', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вісь передня', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Вісь ведуча', ID FROM MALFUNCTION_GROUP WHERE NAME = N'Шасі';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Тягове обладнання', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Пантограф', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Зовнішнє освітлення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Внутрішнє освітлення', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'Органи керування', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
INSERT INTO MALFUNCTION_SUBGROUP(NAME, MALFUNCTION_GROUP_ID) SELECT N'АКБ', ID FROM MALFUNCTION_GROUP WHERE NAME = N'ЕЛО';
GO

INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Зовнішнє облицювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Зовнішнє облицювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Скління', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Скління';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Внутрішнє облицювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Внутрішнє облицювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Сидіння', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Сидіння';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Підлога', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Підлога';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Поручні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Поручні';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Дзеркала', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Дзеркала';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Дверні системи', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Дверні системи';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Трап', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Трап';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система кондиціювання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система кондиціювання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система опалення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система опалення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система інформаційна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система інформаційна';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система відеоспостереження', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Система відеоспостереження';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вузол зчленування', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вузол зчленування';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Двигун тяговий', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Редуктор', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Муфти з’єднувальні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма дискові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма рейкові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь портальна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Елементи підвіски', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система охолодження двигунів', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система подачі піску', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система мащення реборд', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок привідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма дискові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Гальма рейкові', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь портальна', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Елементи підвіски', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Муфти з’єднувальні', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Візок непривідний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система живлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система мащення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система охолодження', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Система нейтралізації викидів', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Двигун дизельний';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'АКПП', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'АКПП';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Карданна передача', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Карданна передача';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь передня', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вісь передня';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Вісь ведуча', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Вісь ведуча';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Тягове обладнання', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Тягове обладнання';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Пантограф', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Пантограф';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Зовнішнє освітлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Зовнішнє освітлення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Внутрішнє освітлення', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Внутрішнє освітлення';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'Органи керування', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'Органи керування';
INSERT INTO MALFUNCTION(NAME, MALFUNCTION_SUBGROUP_ID) SELECT N'АКБ', ID FROM MALFUNCTION_SUBGROUP WHERE NAME = N'АКБ';
GO